In [33]:
import numpy
import pandas as pd
import matplotlib.pyplot
df=pd.read_csv('winequality-white.csv', ';')
df2=df[df['residual sugar']<1]
df3=df2[['pH','density']]
df3=df3[df3.index%2==0]
df3

/srv/conda/envs/notebook/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3441: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
  exec(code_obj, self.user_global_ns, self.user_ns)

        pH  density
54    3.05  0.99300
172   3.03  0.99020
372   3.34  0.99340
1164  3.07  0.99280
1166  3.23  0.99270
1322  3.54  0.99200
1340  3.27  0.99220
1366  3.25  0.99140
1486  3.30  0.99320
2418  3.16  0.99274
2468  3.25  0.99155
2512  3.28  0.99112
2754  3.13  0.98985
2888  3.04  0.99180
2898  2.99  0.99104
2904  3.31  0.99114
2934  3.30  0.99215
2936  3.30  0.99218
2956  2.80  0.99026
2968  2.93  0.99038
2970  2.93  0.99038
2996  3.11  0.98942
3136  3.50  0.99026
3170  3.02  0.99126
3212  3.25  0.99033
3526  3.01  0.98984
3554  2.92  0.99062
3626  3.21  0.99048
3924  2.95  0.99249
4106  3.16  0.99119
4682  3.11  0.98990
4804  3.24  0.98934
4878  3.24  0.99234